[2023-06-16 00:21:32] [ERROR] views - [2023-06-16 00:21:32.096285-03:00] [USER][admin] [IP][127.0.0.1] [ERRO][maximum recursion depth exceeded while calling a Python object]
Traceback (most recent call last):
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/cadastros/views.py", line 467, in cancelar_cliente
    cliente.save()
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/cadastros/models.py", line 150, in save
    self.definir_data_cancelamento()
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/cadastros/models.py", line 165, in definir_data_cancelamento
    mensalidade.save()
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/db/models/base.py", line 861, in save_base
    pre_save.send(
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/cadastros/signals.py", line 128, in criar_nova_mensalidade
    instance.cliente.save()
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/cadastros/models.py", line 150, in save
    self.definir_data_cancelamento()
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/cadastros/models.py", line 158, in definir_data_cancelamento
    old_value = Cliente.objects.get(pk=self.pk).cancelado
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 633, in get
    num = len(clone)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 380, in __len__
    self._fetch_all()
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1547, in execute_sql
    sql, params = self.as_sql()
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 734, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 85, in pre_sql_setup
    order_by = self.get_order_by()
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 457, in get_order_by
    for expr, is_ref in self._order_by_pairs():
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 339, in _order_by_pairs
    selected_exprs[expr] = pos_expr
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/db/models/expressions.py", line 502, in __hash__
    return hash(self.identity)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/db/models/expressions.py", line 479, in identity
    constructor_signature = inspect.signature(self.__init__)
  File "/usr/lib/python3.10/inspect.py", line 3247, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped,
  File "/usr/lib/python3.10/inspect.py", line 2995, in from_callable
    return _signature_from_callable(obj, sigcls=cls,
  File "/usr/lib/python3.10/inspect.py", line 2397, in _signature_from_callable
    sig = _get_signature_of(obj.__func__)
  File "/usr/lib/python3.10/inspect.py", line 2456, in _signature_from_callable
    return _signature_from_function(sigcls, obj,
  File "/usr/lib/python3.10/inspect.py", line 2321, in _signature_from_function
    parameters.append(Parameter(name, annotation=annotation,
  File "/usr/lib/python3.10/inspect.py", line 2632, in __init__
    self._kind = _ParameterKind(kind)
  File "/usr/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
RecursionError: maximum recursion depth exceeded while calling a Python object
[2023-06-16 00:21:32] [ERROR] log - Internal Server Error: /cancelar-cliente/492/
[2023-06-16 00:21:32] [ERROR] basehttp - "POST /cancelar-cliente/492/ HTTP/1.1" 500 69
[2023-06-16 00:21:32] [ERROR] basehttp - "POST /cancelar-cliente/492/ HTTP/1.1" 500 69